name: Build and push image
on:
  workflow_dispatch

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: qbittorrent-wg
        tags: latest
        containerfiles: |
          ./Containerfile

    - name: Push image
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Print image URL
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
